### PR TITLE
Fix login and out button

### LINKED ISSUE #7: Login page behaviour
If a user is logged in and authenticated by Spotify, the main page shows the song details, but no other features at present.

If they return to https://musicjournal-c3d3e.web.app/login there is no indicator that they are logged in.

If they click logout, there is no indicator that logout has been successful, and indeed returning to https://musicjournal-c3d3e.web.app/ shows the songs still, so appears that logout is not occurring.

### PR DESCRIPTION
**Pull request by ChangoFoster**
To fix #7  for now I've made it so that the login button only shows when you logged out and vice versa.

I also moved the getMe util to the auth file where I think we could probably also add in the login function as well.

Logged in screen
image

Logged out screen
image

---
This change is [Reviewable](https://reviewable.io/reviews/jamestwisleton/musicjournal/11)

### CODE REVIEW

File: music-journal/components/Login.js [hunk 1]
```diff
@@ -1,29 +1,36 @@
...
+      setUser()
+    } 
   }
 
   useEffect(() => {
-    if (user) {
-      router.push('/');
+    const getUser = async () => { 
+      try {
+        const [, currentUser] = await getMe()
```
Comment (JamesTwisleton) [inline music-journal/components/Login.js:26]: so this essentially throws away the token variable?

File: music-journal/utils/auth.js [hunk 2]
```diff
@@ -1,13 +1,33 @@
...
         return [firebaseToken, user]
     } catch (error) {
         console.log('auth', error)
     }
 }
+
+const deleteMe = async () => {
+    try {
+        await auth.signOut()
+        Cookies.remove('__session', { path: '' })
```
Comment (JamesTwisleton) [inline music-journal/utils/auth.js:24]: cool!

**Review by JamesTwisleton — APPROVED** [review]

File: music-journal/components/Login.js (hunk 1 above)
Comment (ChangoFoster) [reply music-journal/components/Login.js:26]: yeah I don't think we need it so you just ignore the first item in the array
